module.exports = {
    APP_STORAGE_SECRET_KEY: 'MY_SECRET_KEY_1234',
    APP_STORAGE_USER_ROLE_NAME: 'USER',
    APP_STORAGE_ADMIN_ROLE_NAME: 'ADMIN',
    APP_STORAGE_POWERUSER_ROLE_NAME: 'POWERUSER',
    APP_STORAGE_USER_ROLE_NAME: 'USER',
    APP_STORAGE_USER_TYPE_NAME: 'User',
    APP_STORAGE_GROUP_TYPE_NAME: 'Group',
};
